'use client'

import { ArrowLeft } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useTranslation } from 'react-i18next'

export default function Privacy() {
  const email = 'office@shareyourparty.de'
  const router = useRouter()
  const { i18n } = useTranslation()
  const isEnglish = i18n.language.startsWith('en')

  if (isEnglish) {
    return (
      <div>
        <div className="container mx-auto px-4 py-8 max-w-4xl">
          <button onClick={() => router.back()} className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6">
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
          <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
          <div className="space-y-8 text-foreground">
            <section>
              <h2 className="text-xl font-semibold mb-3">1. Data Controller</h2>
              <p className="text-muted-foreground leading-relaxed">
                The controller responsible for data processing is:<br />
                Sherin Strobl and Mattia Geremicca from Share Your Party<br />
                Email: <a href={`mailto:${email}`} className="text-primary hover:underline">{email}</a>
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">2. Purpose of Data Processing</h2>
              <p className="text-muted-foreground leading-relaxed mb-3">
                The app is being tested as part of a university project and will subsequently be operated as a regular application.
              </p>
              <p className="text-muted-foreground leading-relaxed mb-2">Personal data is processed for the following purposes:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>Provision and operation of the app</li>
                <li>App testing and further development</li>
                <li>User management and login</li>
                <li>Analysis of usage behaviour (optional)</li>
                <li>Processing of optional ticket purchases</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">3. Data Processed</h2>
              <p className="text-muted-foreground leading-relaxed mb-2">Depending on how you use the app, the following data may be processed:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>Login data (e.g. email address or pseudonymous IDs for "Sign in with Apple" / Google)</li>
                <li>Profile data (e.g. username, age, country of residence)</li>
                <li>Usage data (e.g. interactions within the app)</li>
                <li>Device and technical data (e.g. app version, browser)</li>
                <li>Payment data only in the case of a ticket purchase (via external payment providers)</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">4. Legal Bases</h2>
              <p className="text-muted-foreground leading-relaxed mb-2">Processing is based on:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>Art. 6(1)(a) GDPR (consent) – for app use and analytics</li>
                <li>Art. 6(1)(b) GDPR (contract performance) – for ticket purchases</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">5. Analytics</h2>
              <p className="text-muted-foreground leading-relaxed">
                Our websites use Google Analytics, a web analytics service provided by Google Ireland Limited, a company incorporated and operated under Irish law (registration number: 368047) with its registered office at Gordon House, Barrow Street, Dublin 4, Ireland ("Google"). Google uses cookies that enable analysis of your use of the website. The information generated by the cookie about your use of this website (including your IP address) is transmitted to a Google server in the USA and stored there. This website uses Google Analytics with the "anonymize" extension, meaning your IP address is only processed in truncated form, excluding direct personal identification. You can also object to the installation of cookies by downloading a deactivation add-on for your browser. Further information can be found in Google's privacy policy: <a href="https://www.google.com/intl/en/policies/privacy/" className="text-primary hover:underline">www.google.com/intl/en/policies/privacy/</a>
              </p>
              <p className="text-muted-foreground leading-relaxed mt-2">Use of Analytics is voluntary and can be revoked at any time.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">6. Google Remarketing</h2>
              <p className="text-muted-foreground leading-relaxed">
                This website uses cookies to retarget visitors with online advertising at a later point in time via the Google advertising network. To serve remarketing ads, third-party providers such as Google use cookies based on a visit to this website. You can disable Google's use of cookies by visiting <a href="https://myadcenter.google.com/home?hl=en&sasb=true&ref=ad-settings" className="text-primary hover:underline">Google Ad Settings</a> or by opting out via the <a href="https://thenai.org/glossary/opt-out-mechanism/" className="text-primary hover:underline">Network Advertising Initiative opt-out page</a>.
              </p>
              <p className="text-muted-foreground leading-relaxed mt-2">Use of remarketing is voluntary and can be revoked at any time.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">7. Recipients of Data</h2>
              <p className="text-muted-foreground leading-relaxed mb-2">Personal data may be transmitted to the following recipients:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>Google LLC (Firebase, Google Analytics, Google Login)</li>
                <li>Apple Inc. (Sign in with Apple)</li>
                <li>Payment service providers (only for ticket purchases)</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed mt-2">Data processing agreements are in place with all service providers.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">8. Retention Period</h2>
              <p className="text-muted-foreground leading-relaxed">Data is stored for as long as your user account exists or until you withdraw your consent.</p>
              <p className="text-muted-foreground leading-relaxed mt-2">Upon deletion of your account, data will be deleted unless statutory retention obligations apply.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">9. Your Rights</h2>
              <p className="text-muted-foreground leading-relaxed mb-2">You have the right at any time to:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>Access your stored data</li>
                <li>Rectification of inaccurate data</li>
                <li>Deletion of your data</li>
                <li>Withdrawal of your consent</li>
                <li>Restriction of processing</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed mt-2">
                Requests can be directed to <a href={`mailto:${email}`} className="text-primary hover:underline">{email}</a>.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">10. Voluntary Participation</h2>
              <p className="text-muted-foreground leading-relaxed">Use of the app is voluntary.</p>
              <p className="text-muted-foreground leading-relaxed mt-2">Participation or non-participation has no effect on studies, examinations or assessments.</p>
            </section>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div>
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <button onClick={() => router.back()} className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft className="w-4 h-4" />
          Zurück
        </button>
        <h1 className="text-3xl font-bold mb-8">Datenschutzerklärung</h1>
        <div className="space-y-8 text-foreground">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Verantwortlicher</h2>
            <p className="text-muted-foreground leading-relaxed">
              Verantwortlich für die Datenverarbeitung ist:<br />
              Sherin Strobl und Mattia Geremicca von Share Your Party<br />
              E-Mail: <a href={`mailto:${email}`} className="text-primary hover:underline">{email}</a>
            </p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">2. Zweck der Datenverarbeitung</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">Die App wird im Rahmen eines Hochschulprojekts getestet und anschließend als reguläre Anwendung weiterbetrieben.</p>
            <p className="text-muted-foreground leading-relaxed mb-2">Die Verarbeitung personenbezogener Daten erfolgt zu folgenden Zwecken:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Bereitstellung und Betrieb der App</li>
              <li>Durchführung des App-Tests und Weiterentwicklung</li>
              <li>Nutzerverwaltung und Login</li>
              <li>Analyse des Nutzungsverhaltens (optional)</li>
              <li>Abwicklung eines optionalen Ticketkaufs</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">3. Verarbeitete Daten</h2>
            <p className="text-muted-foreground leading-relaxed mb-2">Je nach Nutzung der App werden folgende Daten verarbeitet:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Login-Daten (z. B. E-Mail-Adresse oder pseudonyme IDs bei "Sign in with Apple" / Google)</li>
              <li>Profildaten (z. B. Username, Alter, Wohnsitzland)</li>
              <li>Nutzungsdaten (z. B. Interaktionen innerhalb der App)</li>
              <li>Geräte- und technische Daten (z. B. App-Version, Browser)</li>
              <li>Zahlungsdaten nur im Falle eines Ticketkaufs (über externe Zahlungsanbieter)</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">4. Rechtsgrundlagen</h2>
            <p className="text-muted-foreground leading-relaxed mb-2">Die Verarbeitung erfolgt auf Grundlage von:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Art. 6 Abs. 1 lit. a DSGVO (Einwilligung) – für App-Nutzung und Analytics</li>
              <li>Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung) – bei Ticketkäufen</li>
            </ul>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">5. Analytics</h2>
            <p className="text-muted-foreground leading-relaxed">
              Unsere Websites benutzen Google Analytics, einen Webanalysedienst der Google Ireland Limited, einer nach irischem Recht eingetragenen und betriebenen Gesellschaft (Registernummer: 368047) mit Sitz in Gordon House, Barrow Street, Dublin 4, Irland. („Google"). Diese Website nutzt Google Analytics mit der Erweiterung „anonymize", daher wird Ihre IP-Adresse nur gekürzt weiterverarbeitet. Sie können der Installation der Cookies widersprechen, indem Sie für Ihren Browser ein Deaktivierungs-Add-On herunterladen. Weitere Informationen finden Sie in der Datenschutzerklärung von Google: <a href="https://www.google.com/intl/de/policies/privacy/" className="text-primary hover:underline">www.google.com/intl/de/policies/privacy/</a>
            </p>
            <p className="text-muted-foreground leading-relaxed mt-2">Die Nutzung von Analytics ist freiwillig und kann jederzeit widerrufen werden.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">6. Google Remarketing</h2>
            <p className="text-muted-foreground leading-relaxed">
              Diese Website verwendet Cookies, um Besucher via Remarketing-Kampagnen mit Online Werbung anzusprechen. Sie können die Verwendung von Cookies durch Google unter <a href="https://myadcenter.google.com/home?hl=de&sasb=true&ref=ad-settings" className="text-primary hover:underline">https://adssettings.google.com/authenticated?hl=de</a> oder auf der <a href="https://thenai.org/glossary/opt-out-mechanism/" className="text-primary hover:underline">Deaktivierungsseite der Network Advertising Initiative</a> deaktivieren.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-2">Die Nutzung von Analytics ist freiwillig und kann jederzeit widerrufen werden.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">7. Empfänger der Daten</h2>
            <p className="text-muted-foreground leading-relaxed mb-2">Personenbezogene Daten können an folgende Empfänger übermittelt werden:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Google LLC (Firebase, Google Analytics, Google Login)</li>
              <li>Apple Inc. (Sign in with Apple)</li>
              <li>Zahlungsdienstleister (nur beim Ticketkauf)</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-2">Mit allen Dienstleistern bestehen entsprechende Auftragsverarbeitungsverträge.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">8. Speicherdauer</h2>
            <p className="text-muted-foreground leading-relaxed">Die Daten werden gespeichert, solange dein Nutzerkonto besteht oder bis du deine Einwilligung widerrufst.</p>
            <p className="text-muted-foreground leading-relaxed mt-2">Nach Löschung des Accounts werden die Daten gelöscht, sofern keine gesetzlichen Aufbewahrungspflichten bestehen.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">9. Deine Rechte</h2>
            <p className="text-muted-foreground leading-relaxed mb-2">Du hast jederzeit das Recht auf:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
              <li>Auskunft über deine gespeicherten Daten</li>
              <li>Berichtigung unrichtiger Daten</li>
              <li>Löschung deiner Daten</li>
              <li>Widerruf deiner Einwilligung</li>
              <li>Einschränkung der Verarbeitung</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-2">
              Anfragen kannst du an <a href={`mailto:${email}`} className="text-primary hover:underline">{email}</a> richten.
            </p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">10. Freiwilligkeit</h2>
            <p className="text-muted-foreground leading-relaxed">Die Nutzung der App ist freiwillig.</p>
            <p className="text-muted-foreground leading-relaxed mt-2">Die Teilnahme oder Nicht-Teilnahme hat keine Auswirkungen auf Studium, Prüfungen oder Bewertungen.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
